name: cdk deploy

on:
  push:
    branches:
      - develop
    tags:
      - 'v*'
jobs:
  hischool_deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Setup dependencies
        run: npm install

      - name: Setup env file
        run: npm run build:env -- $apiKey $authDomain $databaseURL $projectId $storageBucket $messagingSenderId $appId $measurementId
        env:
          apiKey: ${{ secrets.apiKey }}
          authDomain: ${{ secrets.authDomain }}
          databaseURL: ${{ secrets.databaseURL }}
          projectId: ${{ secrets.projectId }}
          storageBucket: ${{ secrets.storageBucket }}
          messagingSenderId: ${{ secrets.messagingSenderId }}
          appId: ${{ secrets.appId }}
          measurementId: ${{ secrets.measurementId }}

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "./"
          target: "~/SSR"

      - name: ssh script to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/SSR/hischool.com.vn
            npm run build
            pm2 start npm --name HiSchoolApp -- start src/server/index.js
