name: cdk deploy

on:
  push:
    branches:
      - develop
    tags:
      - 'v*'
jobs:
  hischool_deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Setup env file
        run: bash ./ops/set-env.sh $apiKey $authDomain $databaseURL $projectId $storageBucket $messagingSenderId $appId $measurementId
        env:
          apiKey: ${{ secrets.apiKey }}
          authDomain: ${{ secrets.authDomain }}
          databaseURL: ${{ secrets.databaseURL }}
          projectId: ${{ secrets.projectId }}
          storageBucket: ${{ secrets.storageBucket }}
          messagingSenderId: ${{ secrets.messagingSenderId }}
          appId: ${{ secrets.appId }}
          measurementId: ${{ secrets.measurementId }}

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "./"
          target: "~/SSR/hischool.com.vn"

      - name: ssh script to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/SSR/hischool.com.vn
            NC='\033[0m'
            GREEN='\033[0;32m'
            npm install
            npm install fibers
            printf "${GREEN}Build Packages successful!${NC}\n"
            npm run build
            printf "${GREEN}Build Code successful!${NC}\n"
            rm -rf tmpfile
            rm -rf ssmtmpfile
            printf "${GREEN}Clean uneccessary files!${NC}\n"
            if [ "$(pm2 id hischool-app) "= "[]" ]; then
              pm2 start npm --name hischool-app -- start src/server/index.js
            else
              pm2 restart hischool-app
            fi
            printf "${GREEN}App run!${NC}\n"
